version: "3.9"

services:
  myapp:
    container_name: myapp
    image: dockerstepbystep:latest
    build: .
    ports:
      - "8080:8080"   # host port:container port
    volumes:
      - "./app_data:/var/app_data"    # host directory:container directory
